version: '3'
services:
  flask:
    build: 
      context: .
      network: host
    user: "1000:1000"  
    ports:
      - "5000:5000"  
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    volumes:
      - .:/app
    networks:
      - app_network
  selenium:
    build:
      context: .
      dockerfile: Dockerfile-selenium
    user: "1000:1000"
    depends_on:
      - flask
    environment:
      SE_NODE_MAX_SESSIONS: 1
    networks:
      - app_network

networks:
  app_network:

