FROM selenium/standalone-chrome-debug:3.141.59-zirconium

WORKDIR /app

RUN addgroup appuser && \
    adduser -G appuser -D appuser
USER appuser

RUN apt-get update && apt-get install -y python3 python3-pip

COPY testSelenium.py ./


CMD python3 testSelenium.py

