FROM selenium/node-chrome:4.0.0-rc-1-prerelease-20220224

WORKDIR /app

RUN addgroup appuser && \
    adduser -G appuser -D appuser
USER appuser

RUN apt-get update && apt-get install -y python3 python3-pip

COPY testSelenium.py ./


CMD python3 testSelenium.py

