FROM selenium/standalone-chrome-debug:3.141.59-zirconium

WORKDIR /app

RUN sudo apt update && sudo apt install -y python3 python3-pip

RUN pip3 install selenium

COPY testSelenium.py ./


CMD python3 testSelenium.py

