version: '3'
services:
  flask:
    build: 
      context: .
      network: host
    ports:
      - "5000:5000"  
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    volumes:
      - .:/app
    networks:
      - app_network
  selenium:
    image: selenium/standalone-chrome-debug:3.141.59-zirconium
    user: "1000:1000"
    depends_on:
      - flask
    environment:
      SE_NODE_MAX_SESSIONS: 1
    volumes:
      - ./testSelenium.py:/testSelenium.py
    networks:
      - app_network

networks:
  app_network:

