version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t myimage:latest .
  test:
    docker:
      - image: myimage:latest
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: python3 testApp.py
      - store_test_results:
          path: test-results.xml
      - run:
          name: Send Test Results to Discord
          command: |
            cat test-results.xml

  

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      

