version: 2.1

jobs:
  build-test:
    docker:
      - image: circleci/python
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t myimage:latest .
      - run:
          name: Run & Test
          command: |
            docker run -dit --name=myapp myimage:latest 
            docker exec myapp python testApp.py &> test-results.txt
            cat test-results.txt
      - store_test_results:
          path: test-results.txt
      - run:
          name: Send Test Results
          command: |
            cat test-results.txt
      - run:
          name: push image
          command: |
            docker login -u zoharperets -p $DOCKERHUB_PASS
            docker tag myimage:latest zoharperets/weatherapp:$CIRCLE_BUILD_NUM
            docker push zoharperets/weatherapp:$CIRCLE_BUILD_NUM
  terraform-tests:
    working_directory: ~/project/gitops-repo
    docker:
      - image: hashicorp/terraform:1.0.8
    steps:
      - run:
          name: Clone Repo
          command: |
            git clone https://github.com/zoharperetz/prod.git
      - run:
         name: tests
         command: |
           pwd
           ls -a


 

workflows:
  build-test-deploy:
    jobs:
      - build-test
      - terraform-tests:
          requires:
            - build-test
     
      

