version: 2.1

jobs:
  build-test:
    docker:
      - image: circleci/python
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t myimage:latest .
      - run:
          name: Run & Test
          command: |
            docker run -dit --name=myapp myimage:latest 
            docker exec myapp python testApp.py &> test-results.txt
            cat test-results.txt
      - store_test_results:
          path: test-results.txt
      - run:
          name: Send Test Results
          command: |
            cat test-results.txt
      - run:
          name: push image
          command: |
            docker login -u zoharperets -p $DOCKERHUB_PASS
            docker tag myimage:latest zoharperets/weatherapp:$CIRCLE_BUILD_NUM
            docker push zoharperets/weatherapp:$CIRCLE_BUILD_NUM
  terraform-tests:
    docker:
      - image: ubuntu:latest
    steps:
      - run:
          name: Update apt-get and install dependencies
          command: |
            apt-get update
            apt-get install -y curl unzip
            apt-get install -y git
            export PATH=$PATH:/usr/bin/git

      - run:
          name: Install Go
          command: |
            curl -O https://dl.google.com/go/go1.16.4.linux-amd64.tar.gz
            tar -C /usr/local -xvf go1.16.4.linux-amd64.tar.gz
            export PATH=$PATH:/usr/local/go/bin
            go version
      - run:
          name: Install Terraform
          command: |
            curl -O https://releases.hashicorp.com/terraform/1.0.3/terraform_1.0.3_linux_amd64.zip
            unzip terraform_1.0.3_linux_amd64.zip
            mv terraform /usr/local/bin/
      - run:
          name: Clone Repo
          command: |
            git clone https://zoharperetz:$GITHUB_TOKEN@github.com/zoharperetz/prod.git
      - run:
          name: Run Terratest
          command: |
            cd prod/test
            export PATH=$PATH:/usr/local/go/bin
            go mod init test_eks
            go mod tidy
            go test -v 


workflows:
  build-test-deploy:
    jobs:
      - build-test
      - terraform-tests:
          requires:
            - build-test
     
      

