version: 2.1

orbs:
  docker-publish: haskell-works/docker-publish@1.0.0

jobs:
  build-test:
    docker:
      - image: circleci/python
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t myimage:latest .
      - run:
          name: Run & Test
          command: |
            docker run -dit --name=myapp myimage:latest 
            docker exec myapp python testApp.py &> test-results.txt
            cat test-results.txt
      - store_test_results:
          path: test-results.txt
      - run:
          name: Send Test Results
          command: |
            cat test-results.txt
      - docker-publish/publish:
          context: .
          dockerfile: Dockerfile
          repository: zoharperets/weatherapp
          tag: myimage:$CIRCLE_BUILD_NUM
          username: zoharperets
          password: $DOCKERHUB_PASS

 

workflows:
  build-test-deploy:
    jobs:
      - build-test
     
      

