version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t myimage:latest .
            pwd
            ls -a
      - persist_to_workspace:
          root: .
          paths:
            - Dockerfile
            - myimage.tar
          when: always
  test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Unit Tests
          command: |
            docker load -i /home/circleci/project/myimage.tar
            docker run -dit myimage python testApp.py
      - store_test_results:
          path: test-results.xml
      - run:
          name: Send Test Results to Discord
          command: |
            cat test-results.xml

  

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      

