version: 2.1

jobs:
  build-test:
    docker:
      - image: circleci/python
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t myimage:latest .
      - run:
          name: Run & Test
          command: |
            docker run -dit --name=myapp myimage:latest 
            docker exec myapp python testApp.py &> test-results.txt
            cat test-results.txt
      - store_test_results:
          path: test-results.txt
      - run:
          name: Send Test Results
          command: |
            cat test-results.txt
      - run:
          name: push image
          command: |
            docker login -u zoharperets -p $DOCKERHUB_PASS
            docker tag myimage:latest zoharperets/weatherapp:$CIRCLE_BUILD_NUM
            docker push zoharperets/weatherapp:$CIRCLE_BUILD_NUM
  terraform-tests:
    working_directory: ~/project/gitops-repo
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - run:
          name: Setup
          command: |
            apt-get install -y golang
            export PATH=$PATH:/usr/local/go/bin
      - run:
          name: Clone Repo
          command: |
            git clone https://zoharperetz:$GITHUB_TOKEN@github.com/zoharperetz/prod.git
      - run:
          name: Run Terratest
          command: |
            ls -a
            cd prod/test
            pwd
            go mod init test_eks
            go mod tidy
            go test -v 


 

workflows:
  build-test-deploy:
    jobs:
      - build-test
      - terraform-tests:
          requires:
            - build-test
     
      

