apiVersion: v1
kind: Service
metadata:
  name: weatherapp-service
  labels:
    app: weather-app
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: weather-app
